services:
  laundry-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-volume:/var/lib/capt_laundry_bot
    environment:
      BASE_PATH: /var/lib/capt_laundry_bot
    restart: unless-stopped
    ports:
      - "3000:80"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - laundry-bot
    restart: always
    volumes:
      - static-volume:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  static-volume:
