services:
  laundry-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static-volume:/var/lib/capt_laundry_bot
    environment:
      BASE_PATH: /var/lib/capt_laundry_bot
volumes:
  static-volume:
